In [1]:
from sklearn.decomposition import PCA

In [9]:
pca = PCA(n_components=2)

In [3]:
import numpy as np
x = np.array([[1,2,3,4,5],[-1,-2,3,4,5], [1,-2,3,4,5]])

In [6]:
pca.fit(x)

PCA(n_components=2)

In [5]:
principalComponents

array([[ 2.74543484, -0.13469638],
       [-1.66250157, -0.88974384],
       [-1.08293327,  1.02444022]])

In [8]:
pca.transform(np.array([[1,2,3,4,5]]))

array([[ 2.74543484, -0.13469638]])

In [10]:
y = [np.array([1,2,3,4,5]), np.array([-1,-2,3,4,5]), np.array([1,-2,3,4,5])]

In [11]:
pca.fit(y)

PCA(n_components=2)

In [15]:
pca.transform([np.array([1,2,3,4,5]), np.array([1,2,3,4,5])])

array([[ 2.74543484, -0.13469638],
       [ 2.74543484, -0.13469638]])